Repository NBC4-Outsourcing/zarani, pull requests merged in 2024-02, with the labels that each got.

#9 [Feat/#4] 마이페이지 생성 및 기본 틀 구축, Route 추가, useInput.js - useState훅 구성 등
  src/assets/defaultImage.png
  src/components/styles/myPageStyle.js
  src/hooks/useInput.js
  src/pages/MyPage.jsx
  src/shared/Router.jsx
  src/shared/redux/config/configStore.js
  src/shared/redux/modules/userSlice.js
Labels: documentation, enhancement

#22 Main page 레이아웃
  src/assets/kangwondo.png
  src/assets/logo.png
  src/components/comunityComponents/supabaseTest.js
  src/components/mainPage/MainPage.jsx
  src/components/mainPage/MainPageComunity.jsx
  src/components/mainPage/MainPageHeader.jsx
  src/components/mainPage/MainPageMap.jsx
  src/components/mainPage/MainPageNav.jsx
  src/components/mainPageComponent/MainPage.jsx
  src/components/mainPageComponent/MainPageHeader.jsx
  src/components/mainPageComponent/mainPageHeaderStyle.js
  src/components/styles/mainPageStyle.js
  src/shared/Router.jsx
Labels: documentation, enhancement

#23 [feat/#4] - reviewPage 생성 및 구성
  .env
  src/assets/reviewTestImg.png
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/reviewSupabase.js
  src/shared/Router.jsx
Labels: documentation, enhancement

#27 [Feat/#25] - supabase 스토리지 연결, supabase 설정 js 생성, .env 삭제, env.local로 써주시거나 .gitignore에 .env 등록해주셔용
  .env
  src/api/supabase/supabase.js
  src/components/comunityComponents/supabaseTest.js
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/components/styles/MyPageStyle.jsx
  src/components/styles/myPageStyle.js
  src/pages/MyPage.jsx
  src/shared/redux/modules/userSlice.js
Labels: documentation, enhancement

#28 Comunity supabase.js 설정 적용
  src/api/supabase/supabase.js
  src/components/comunityComponents/CommentInputForm.jsx
  src/components/comunityComponents/CommentList.jsx
  src/components/comunityComponents/ComunityInputForm.jsx
  src/components/comunityComponents/ComunitySupabase.js
  src/components/comunityComponents/ComunityWriteEditForm.jsx
  src/components/comunityComponents/WritingList.jsx
  src/components/styles/ComunityStyle.js
Labels: documentation, enhancement

#29 [feat/#24] - 이미지 미리보기 생성
  src/assets/imageFrame.png
  src/assets/reviewTestImg.png
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/reviewSupabase.js
  src/components/styles/ReviewStyle.jsx
  src/pages/Review.jsx
Labels: documentation, enhancement

#31 [Feat/#19] - 로그인/회원가입 페이지 레이아웃 설정, 라우팅 초기 설
  src/components/loginPageComponents/LoginInputForm.jsx
  src/components/styles/LoginStyle.js
  src/pages/Login.jsx
  src/shared/Router.jsx
Labels: documentation, enhancement

#34 [Feat/bug/#33] - 마이페이지 유저정보 db 저장 및 가져오기, 수정기능 완료/ 이미지 주소 형태 오류 해결 중
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/pages/MyPage.jsx
  src/shared/redux/modules/userSlice.js
Labels: documentation, enhancement

#43 [feat/#30] - 후기글 등록 기능 구현
  src/assets/imageFrame.png
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/pages/Review.jsx
  src/pages/ReviewPage.jsx
  src/shared/Router.jsx
Labels: documentation, enhancement

#45 Main page
  package.json
  public/index.html
  src/assets/2.png
  src/assets/3.png
  src/assets/4.png
  src/assets/5.png
  src/assets/6.png
  src/assets/7.png
  src/components/mainPage/MainPageComunity.jsx
  src/components/mainPage/MainPageHeader.jsx
  src/components/mainPage/MainPageKaKao.jsx
  src/components/mainPage/MainPageMap.jsx
  src/components/mainPage/MainPageNav.jsx
  src/components/styles/mainPageStyle.js
  src/shared/redux/config/configStore.js
  src/shared/redux/modules/areaSlice.js
  yarn.lock
Labels: documentation, enhancement

#47 [Feat/#46] 마이페이지 내가 쓴 후기 구현
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/pages/MyPage.jsx
  src/shared/redux/modules/userSlice.js
Labels: documentation, enhancement

#48 [Feat/#46] 마이페이지 조회 오타수정
  src/components/myPageComponent/MyPageContents.jsx
Labels: documentation, enhancement

#49 [feat/#37] - 로그인/회원가입 기능 구현 및 기본 프로필 이미지 추가
  src/assets/defaultProfileImage.png
  src/components/loginPageComponents/LoginInputForm.jsx
  src/pages/Login.jsx
Labels: documentation, enhancement

#50 Comunity 오탈자 수정
  src/components/communityComponents/CommentInputForm.jsx
  src/components/communityComponents/CommentList.jsx
  src/components/communityComponents/CommunityInputForm.jsx
  src/components/communityComponents/CommunityMain.jsx
  src/components/communityComponents/CommunitySupabase.js
  src/components/communityComponents/CommunityWriteEditForm.jsx
  src/components/communityComponents/WritingList.jsx
  src/components/communityComponents/formattedDate.js
  src/components/comunityComponents/WritingList.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/styles/CommunityStyle.js
  src/pages/Comunity.jsx
Labels: documentation

#53 [Feat/#52] 리액트 쿼리 리팩토링
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/pages/MyPage.jsx
Labels: enhancement

#59 [feat/#58] - 로그인한 유저의 정보를 가져오는 로직 추가
  src/utils/getLocalStorageJSON.js
Labels: documentation, enhancement

#61 [feat] - 로그인 상태에 따른 조건부 렌더링 구현
  src/components/loginPageComponents/LoginInputForm.jsx
  src/components/mainPage/MainPageHeader.jsx
  src/components/styles/mainPageStyle.js
  src/shared/redux/config/configStore.js
  src/shared/redux/modules/authSlice.js
  src/utils/getLocalStorageJSON.js
Labels: documentation, enhancement

#63 [fix] 후기 글 등록, 이미지 등록, 후기 리스트 기능 오류 수정 완료
  src/components/myPageComponent/myPageSupabase.js
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/reviewComponents/reviewSupabase.js
Labels: documentation, enhancement

#68 [Feat/#66]이미지 업로드 버그 해결 ㅠㅠㅠ 원인은 브라우져 캐싱문제로 !
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/components/styles/MyPageHeaderStyle.jsx
  src/pages/MyPage.jsx
Labels: bug, documentation, enhancement

#73 [Feat/#72] MyPage 로그인 상태 기준 페이지 접근 설정
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/shared/redux/config/configStore.js
  src/shared/redux/modules/userSlice.js
Labels: documentation, enhancement

#75 [Feat/#74] 마이 페이지 id 에러처리 및 리액트 쿼리로 다시 리팩토링 중
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/myPageSupabase.js
  src/pages/MyPage.jsx
Labels: documentation, enhancement

#76 [Fix/#74]마이 페이지 id 에러처리 및 리액트 쿼리로 다시 리팩토링 중
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/myPageSupabase.js
Labels: bug, documentation

#77 Comunity 에러 핸들링 세분화 및 스타일링 pr
  src/components/communityComponents/CommentList.jsx
  src/components/communityComponents/CommunitySupabase.js
  src/components/myPageComponent/MyPageContents.jsx
  src/components/styles/CommunityStyle.js
  src/pages/Community.jsx
Labels: documentation, enhancement

#79 [Feat,Fix,Bug/#78] - 리액트 쿼리 적용 후 이미지 버그 삼중주 중 이중주 해결
  src/components/myPageComponent/MyPageContents.jsx
Labels: bug, documentation, enhancement

#84 [Feat #67] 리뷰 게시물 수정 기능 구현, 삭제 기능 수정
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/reviewComponents/ReviewUpdateForm.jsx
  src/shared/Router.jsx
Labels: documentation, enhancement

#88 Comunity 유효성 검사 및 css 수정
  src/components/communityComponents/CommentInputForm.jsx
  src/components/communityComponents/CommentList.jsx
  src/components/communityComponents/CommunityHeader.jsx
  src/components/communityComponents/CommunityInputForm.jsx
  src/components/communityComponents/CommunitySupabase.js
  src/components/communityComponents/CommunityWriteEditForm.jsx
  src/components/communityComponents/WritingList.jsx
  src/components/styles/CommunityStyle.js
  src/pages/Community.jsx
Labels: documentation, enhancement

#94 [feat/#93] - 회원가입 시 기본 아바타 적용
  src/components/loginPageComponents/LoginInputForm.jsx
Labels: documentation, enhancement

#95 [feat #67] 리뷰 이미지 수정기능 수정 중
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/reviewComponents/ReviewUpdateForm.jsx
  src/components/styles/ReviewStyle.jsx
Labels: documentation, enhancement

#97 [feat] - 중복 로그인 처리 기능 구현
  src/components/loginPageComponents/LoginInputForm.jsx
  src/components/loginPageComponents/loginPageSupabase.js
  src/components/mainPage/MainPageHeader.jsx
Labels: documentation, enhancement

#98 [Style/#92]MyPage css 완성
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/styles/MyPageContentsStyle.js
  src/components/styles/MyPageContentsStyle.jsx
  src/components/styles/MyPageHeaderStyle.jsx
  src/components/styles/MyPageReviews.js
  src/components/styles/MyPageStyle.jsx
  src/pages/MyPage.jsx
Labels: documentation, enhancement

#103 [Feat/#102] - 마이페이지 접근 설정 수정 로그인 상태에 따른 로그아웃 제거
  src/components/myPageComponent/MyPageContents.jsx
  src/components/styles/GlobalStyle.jsx
  src/components/styles/MyPageContentsStyle.js
  src/components/styles/MyPageHeaderStyle.jsx
Labels: documentation

#106 [style #99] 화면 자동 새로고침 적용중
  src/assets/check.gif
  src/assets/zarani.png
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewHeader.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/reviewComponents/ReviewUpdateForm.jsx
  src/components/styles/ReviewStyle.jsx
  src/pages/ReviewPage.jsx
Labels: documentation, enhancement

#107 Feat/#105] null값이 들어가지 않도록 이미지 선택해야 수정 가능하게 유효성 처리
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/myPageComponent/MyPageReviews.jsx
Labels: bug, documentation, enhancement

#113 [style/#112] - 로그인페이지 로고 이미지 높이 수정
  src/components/styles/LoginStyle.js
Labels: documentation, enhancement

#115 [Chore] 안 쓰는 코드 삭제
  src/components/myPageComponent/MyPageContents.jsx
  src/components/myPageComponent/MyPageReviews.jsx
  src/components/myPageComponent/myPageSupabase.js
Labels: documentation

#120 [fix] 리뷰 게시물 정렬 수정
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/styles/ReviewStyle.js
Labels: documentation, enhancement

#123 [Refactor/#121]- 피드백 반영 - MyPage 내가 쓴 후기 정렬 위치 조정
  README.md
  src/components/myPageComponent/MyPageContents.jsx
  src/components/reviewComponents/ReviewForm.jsx
  src/components/reviewComponents/ReviewList.jsx
  src/components/styles/MyPageContentsStyle.js
  src/components/styles/MyPageReviews.js
  src/components/styles/ReviewStyle.js
Labels: documentation, enhancement

#126 Main page
  src/components/mainPage/MainPageKaKao.jsx
  src/components/mainPage/MainPageList.jsx
  src/pages/MainPage.jsx
  src/shared/redux/config/configStore.js
  src/shared/redux/modules/mapListSlice.js
Labels: documentation, enhancement

#134 [Style/#132] - MyPage 헤더에 로고 추가
  src/components/myPageComponent/MyPageHeader.jsx
  src/components/styles/MyPageContentsStyle.js
  src/components/styles/MyPageHeaderStyle.js
Labels: documentation
